// src/routes/embedText.ts
//
// POST /ucp/embed-text — text → 512-d vector transcoder.
//
// Spawned to back the Embedding Lab's "Transcode" button: instead of
// pasting 512 floats by hand, paste a short text and get a vector
// generated by the SAME engine the catalog uses for embedSignal().
// This guarantees the resulting vector lives in the same space_id as
// catalog signal vectors, so cosine comparisons via /ucp/query-vector
// are valid.
//
// Engine selection follows createEmbeddingEngine: EMBEDDING_ENGINE=llm
// + OPENAI_API_KEY → live OpenAI text-embedding-3-small (512-d);
// otherwise PseudoEmbeddingEngine (deterministic DJB2 hash, useful for
// demo + tests but not semantically meaningful).
//
// Auth: same demo-tier posture as /ucp/query-vector. Read-only on the
// engine side — no D1 writes, no KV writes, no side effects.

import type { Env } from "../types/env";
import type { Logger } from "../utils/logger";
import { jsonResponse, errorResponse, readJsonBody } from "./shared";
import { createEmbeddingEngine } from "../ucp/embeddingEngine";

interface EmbedTextRequest {
  text?: string;
}

interface EmbedTextResponse {
  vector: number[];
  dim: number;
  space_id: string;
  engine_phase: string;
  duration_ms: number;
  /**
   * The engine doesn't expose its model_id directly; we emit a
   * derived label so the UI can render "openai-te3-small-d512-v1"
   * vs "adcp-bridge-space-v1.0" without coupling to the class shape.
   */
  model_label: string;
  /**
   * Echo of the input text (truncated to 200 chars for safety).
   * Lets the UI confirm what was actually transcoded.
   */
  input_text: string;
}

const MAX_TEXT_BYTES = 4_096; // 4 KB — generous for a query string, blocks dump-the-novel abuse
const MAX_TEXT_PREVIEW = 200;

export async function handleEmbedText(
  request: Request,
  env: Env,
  logger: Logger,
): Promise<Response> {
  if (request.method !== "POST") {
    return errorResponse("METHOD_NOT_ALLOWED", "POST required", 405);
  }

  const bodyResult = await readJsonBody<EmbedTextRequest>(request);
  if (bodyResult.kind === "invalid") {
    return errorResponse("INVALID_BODY", bodyResult.reason, 400);
  }
  const body = bodyResult.kind === "parsed" ? bodyResult.data : null;
  const text = (body?.text ?? "").trim();

  if (!text) {
    return errorResponse("INVALID_BODY", "Missing required field: text", 400);
  }
  // UTF-8 byte cap — JS string length undercounts emoji / CJK, so use TextEncoder.
  const byteLen = new TextEncoder().encode(text).length;
  if (byteLen > MAX_TEXT_BYTES) {
    return errorResponse(
      "INVALID_BODY",
      `text too long (${byteLen} bytes; cap ${MAX_TEXT_BYTES})`,
      400,
    );
  }

  const t0 = Date.now();
  const engine = createEmbeddingEngine(env);
  let vector: number[];
  try {
    vector = await engine.embedText(text);
  } catch (err) {
    logger.error("embed_text_failed", {
      error: String(err),
      engine_phase: engine.phase,
      space_id: engine.spaceId,
    });
    return errorResponse(
      "EMBEDDING_FAILED",
      `embedding engine threw: ${(err as Error).message ?? String(err)}`,
      502,
    );
  }
  const duration_ms = Date.now() - t0;

  const modelLabel = engine.phase === "pseudo-v1"
    ? "adcp-bridge-pseudo-v1.0"
    : "text-embedding-3-small";

  const response: EmbedTextResponse = {
    vector,
    dim: vector.length,
    space_id: engine.spaceId,
    engine_phase: engine.phase,
    duration_ms,
    model_label: modelLabel,
    input_text: text.length > MAX_TEXT_PREVIEW ? text.slice(0, MAX_TEXT_PREVIEW) + "…" : text,
  };

  logger.info("embed_text_ok", {
    dim: vector.length,
    engine_phase: engine.phase,
    space_id: engine.spaceId,
    duration_ms,
    text_bytes: byteLen,
  });

  return jsonResponse(response);
}
