// tests/proposal-cache.test.ts
// Covers the search -> KV cache -> activate -> D1 promotion flow.

import { describe, it, expect, vi } from "vitest";
import { putProposal, getProposal, deleteProposal } from "../src/storage/proposalCache";
import { proposalToCanonical } from "../src/domain/signalService";
import { activateSignalService, NotFoundError } from "../src/domain/activationService";
import type { CanonicalSignal } from "../src/types/signal";
import type { CustomSignalProposal, ActivateSignalRequest } from "../src/types/api";

// ── Fakes ─────────────────────────────────────────────────────────────────────

function makeKv(): KVNamespace {
  const store = new Map<string, string>();
  return {
    async get(key: string) { return store.get(key) ?? null; },
    async put(key: string, value: string) { store.set(key, value); },
    async delete(key: string) { store.delete(key); },
    async list() { return { keys: [...store.keys()].map(name => ({ name })), list_complete: true } as never; },
    async getWithMetadata() { return { value: null, metadata: null } as never; },
  } as unknown as KVNamespace;
}

interface CapturedExec { sql: string; params: unknown[] }

function makeDb(opts: { signalRows?: CapturedExec[] } = {}): { db: D1Database; calls: CapturedExec[] } {
  const calls: CapturedExec[] = [];
  // Minimal D1 fake — only the methods activationService + signalRepo touch.
  const db = {
    prepare(sql: string) {
      let bound: unknown[] = [];
      return {
        bind(...args: unknown[]) { bound = args; return this; },
        async first<T>() {
          calls.push({ sql, params: bound });
          // Default: signal not in catalog (forces cache lookup).
          // For activation_jobs lookups, return null too.
          return null as unknown as T;
        },
        async all<T>() {
          calls.push({ sql, params: bound });
          return { results: [] as T[] };
        },
        async run() {
          calls.push({ sql, params: bound });
          return { success: true, meta: {} } as unknown as D1Result;
        },
      };
    },
    async batch(stmts: Array<{ run: () => Promise<D1Result> }>) {
      const out = [];
      for (const s of stmts) out.push(await s.run());
      return out;
    },
  } as unknown as D1Database;
  return { db, calls };
}

const sampleProposal: CustomSignalProposal = {
  signal_agent_segment_id: "sig_dyn_test_abc123",
  name: "Test Proposal",
  description: "Generated by a test brief.",
  signal_type: "custom",
  category_type: "demographic",
  estimated_audience_size: 1_000_000,
  coverage_percentage: 1.5,
  pricing_options: [],
  deployments: [],
  generation_rationale: "test",
};

const fakeLogger = {
  debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn(),
} as never;

// ── proposalCache CRUD ────────────────────────────────────────────────────────

describe("proposalCache", () => {
  it("round-trips a CanonicalSignal through put/get", async () => {
    const kv = makeKv();
    const canonical = proposalToCanonical(sampleProposal, "2026-04-19T00:00:00Z");
    await putProposal(kv, canonical);

    const got = await getProposal(kv, sampleProposal.signal_agent_segment_id);
    expect(got).toEqual(canonical);
  });

  it("returns null on miss", async () => {
    const kv = makeKv();
    expect(await getProposal(kv, "sig_does_not_exist")).toBeNull();
  });

  it("returns null on corrupt JSON in cache", async () => {
    const kv = makeKv();
    await kv.put("proposal:sig_bad", "{not-json");
    expect(await getProposal(kv, "sig_bad")).toBeNull();
  });

  it("delete removes the entry", async () => {
    const kv = makeKv();
    const canonical = proposalToCanonical(sampleProposal, "2026-04-19T00:00:00Z");
    await putProposal(kv, canonical);
    await deleteProposal(kv, canonical.signalId);
    expect(await getProposal(kv, canonical.signalId)).toBeNull();
  });
});

// ── proposalToCanonical contract ──────────────────────────────────────────────

describe("proposalToCanonical", () => {
  it("preserves signalId, name, audience size; sets dynamic generation mode", () => {
    const c = proposalToCanonical(sampleProposal, "2026-04-19T00:00:00Z");
    expect(c.signalId).toBe(sampleProposal.signal_agent_segment_id);
    expect(c.name).toBe(sampleProposal.name);
    expect(c.estimatedAudienceSize).toBe(sampleProposal.estimated_audience_size);
    expect(c.generationMode).toBe("dynamic");
    expect(c.activationSupported).toBe(true);
    expect(c.destinations).toContain("mock_dsp");
  });
});

// ── activateSignalService cache promotion ─────────────────────────────────────

describe("activateSignalService — KV cache lookup", () => {
  function req(signalId: string): ActivateSignalRequest {
    return { signalId, destination: "mock_dsp" };
  }

  it("404s when signal is missing in D1, request, AND cache", async () => {
    const { db } = makeDb();
    const kv = makeKv();
    await expect(
      activateSignalService(db, kv, req("sig_unknown"), fakeLogger)
    ).rejects.toBeInstanceOf(NotFoundError);
  });

  it("promotes a cached proposal: lazy-creates in D1 and evicts from KV", async () => {
    const { db, calls } = makeDb();
    const kv = makeKv();
    const canonical = proposalToCanonical(sampleProposal, "2026-04-19T00:00:00Z");
    await putProposal(kv, canonical);

    const result = await activateSignalService(db, kv, req(canonical.signalId), fakeLogger);

    expect(result.task_id).toMatch(/^op_/);
    expect(result.signal_agent_segment_id).toBe(canonical.signalId);

    // D1 received an INSERT/UPSERT for the signal (lazy create).
    const upsertCall = calls.find(c => /INSERT INTO signals/.test(c.sql));
    expect(upsertCall).toBeDefined();
    expect(upsertCall!.params[0]).toBe(canonical.signalId);

    // KV eviction happened (best-effort).
    expect(await getProposal(kv, canonical.signalId)).toBeNull();
  });

  it("honours explicit proposalData on the request (legacy path) before consulting cache", async () => {
    const { db, calls } = makeDb();
    const kv = makeKv();
    // Cache contains a different proposal — request data should win.
    const cached = proposalToCanonical(sampleProposal, "2026-04-19T00:00:00Z");
    await putProposal(kv, cached);

    const requestProposal: CanonicalSignal = {
      ...cached,
      signalId: "sig_dyn_explicit",
      name: "Explicit",
    };
    const result = await activateSignalService(
      db, kv,
      { signalId: requestProposal.signalId, destination: "mock_dsp", proposalData: requestProposal },
      fakeLogger,
    );

    expect(result.signal_agent_segment_id).toBe(requestProposal.signalId);
    const upsertCall = calls.find(c => /INSERT INTO signals/.test(c.sql));
    expect(upsertCall!.params[0]).toBe(requestProposal.signalId);
    // Cache entry for the unrelated `cached` signal is not touched.
    expect(await getProposal(kv, cached.signalId)).not.toBeNull();
  });
});
